### PR TITLE
Assets

### PR DESCRIPTION
**Pull request by foresterre**

### CODE REVIEW

**Comment by NickTUD** [comment]
Make sure the build completes first

**Comment by foresterre** [comment]
The tests fail on a HTTP request timeout of travis. Have requested a rebuild on travis.

**Comment by foresterre** [comment]
What probably is going wrong:
Multiple methods are set to 'final' (checkstyle tries to enforce this). 
However, when a method is final, no longer a stub can be made.

**Comment by foresterre** [comment]
Builds failed on accelerometer tests, hence I've pulled (and unfortunately merged) from dev.

**Comment by sirpolomotro** [comment]
Sounds should not be streamed (not music) And is will close the app (keep it in memory) and re open it than all the buttons (planks) are images of the background.

**Pull request closed without merging**
